var hierarchy =
[
    [ "xaimassist::app::Application", "classxaimassist_1_1app_1_1Application.html", null ],
    [ "xaimassist::core::events::ApplicationLifecycleEvent", "structxaimassist_1_1core_1_1events_1_1ApplicationLifecycleEvent.html", null ],
    [ "xaimassist::persistence::AppSettings", "structxaimassist_1_1persistence_1_1AppSettings.html", null ],
    [ "xaimassist::engine::CameraBackend", "classxaimassist_1_1engine_1_1CameraBackend.html", null ],
    [ "xaimassist::engine::CameraBackend::CameraPose", "structxaimassist_1_1engine_1_1CameraBackend_1_1CameraPose.html", null ],
    [ "xaimassist::world::ColliderComponent", "structxaimassist_1_1world_1_1ColliderComponent.html", null ],
    [ "xaimassist::persistence::ColorRgb", "structxaimassist_1_1persistence_1_1ColorRgb.html", null ],
    [ "xaimassist::app::CompositionRoot", "classxaimassist_1_1app_1_1CompositionRoot.html", null ],
    [ "xaimassist::persistence::CrosshairPreferences", "structxaimassist_1_1persistence_1_1CrosshairPreferences.html", null ],
    [ "xaimassist::app::TrainingFlowController::Deps", "structxaimassist_1_1app_1_1TrainingFlowController_1_1Deps.html", null ],
    [ "xaimassist::engine::Engine", "classxaimassist_1_1engine_1_1Engine.html", null ],
    [ "xaimassist::app::PerformanceClassifier::EvaluatedMetricComparison", "structxaimassist_1_1app_1_1PerformanceClassifier_1_1EvaluatedMetricComparison.html", null ],
    [ "xaimassist::core::EventBus", "classxaimassist_1_1core_1_1EventBus.html", null ],
    [ "xaimassist::input::FireAction", "structxaimassist_1_1input_1_1FireAction.html", null ],
    [ "xaimassist::persistence::FpsCounterPreferences", "structxaimassist_1_1persistence_1_1FpsCounterPreferences.html", null ],
    [ "xaimassist::core::FrameClock", "classxaimassist_1_1core_1_1FrameClock.html", null ],
    [ "xaimassist::core::events::FrameTickEvent", "structxaimassist_1_1core_1_1events_1_1FrameTickEvent.html", null ],
    [ "xaimassist::gameplay::GameMode", "classxaimassist_1_1gameplay_1_1GameMode.html", [
      [ "xaimassist::gameplay::GridShotMode", "classxaimassist_1_1gameplay_1_1GridShotMode.html", null ],
      [ "xaimassist::gameplay::NextShotMode", "classxaimassist_1_1gameplay_1_1NextShotMode.html", null ],
      [ "xaimassist::gameplay::StaticSphereMode", "classxaimassist_1_1gameplay_1_1StaticSphereMode.html", null ],
      [ "xaimassist::gameplay::StrafingTargetsMode", "classxaimassist_1_1gameplay_1_1StrafingTargetsMode.html", null ],
      [ "xaimassist::gameplay::TrackingTargetsMode", "classxaimassist_1_1gameplay_1_1TrackingTargetsMode.html", null ]
    ] ],
    [ "xaimassist::gameplay::GameModeMetadata", "structxaimassist_1_1gameplay_1_1GameModeMetadata.html", null ],
    [ "xaimassist::gameplay::GameModeRegistry", "classxaimassist_1_1gameplay_1_1GameModeRegistry.html", null ],
    [ "xaimassist::gameplay::GameModeSettingMetadata", "structxaimassist_1_1gameplay_1_1GameModeSettingMetadata.html", null ],
    [ "xaimassist::persistence::GameplayPreferences", "structxaimassist_1_1persistence_1_1GameplayPreferences.html", null ],
    [ "xaimassist::gameplay::GameplayRuntimeSettings", "structxaimassist_1_1gameplay_1_1GameplayRuntimeSettings.html", null ],
    [ "xaimassist::gameplay::HitTestResult", "structxaimassist_1_1gameplay_1_1HitTestResult.html", null ],
    [ "xaimassist::ui::I18nProvider", "classxaimassist_1_1ui_1_1I18nProvider.html", null ],
    [ "xaimassist::gameplay::IGameplaySettingsProvider", "classxaimassist_1_1gameplay_1_1IGameplaySettingsProvider.html", [
      [ "xaimassist::app::AppGameplaySettingsProvider", "classxaimassist_1_1app_1_1AppGameplaySettingsProvider.html", null ]
    ] ],
    [ "xaimassist::gameplay::IHitTestService", "classxaimassist_1_1gameplay_1_1IHitTestService.html", [
      [ "xaimassist::app::WorldRaycastHitTest", "classxaimassist_1_1app_1_1WorldRaycastHitTest.html", null ]
    ] ],
    [ "xaimassist::persistence::InputPreferences", "structxaimassist_1_1persistence_1_1InputPreferences.html", null ],
    [ "xaimassist::world::IRenderSceneBackend", "classxaimassist_1_1world_1_1IRenderSceneBackend.html", [
      [ "xaimassist::app::EngineRenderBridge", "classxaimassist_1_1app_1_1EngineRenderBridge.html", null ]
    ] ],
    [ "xaimassist::gameplay::ISceneCommandSink", "classxaimassist_1_1gameplay_1_1ISceneCommandSink.html", [
      [ "xaimassist::app::GameplayWorldBridge", "classxaimassist_1_1app_1_1GameplayWorldBridge.html", null ]
    ] ],
    [ "xaimassist::persistence::KeyBindingsPreferences", "structxaimassist_1_1persistence_1_1KeyBindingsPreferences.html", null ],
    [ "xaimassist::core::Logger", "classxaimassist_1_1core_1_1Logger.html", null ],
    [ "xaimassist::input::LookAction", "structxaimassist_1_1input_1_1LookAction.html", null ],
    [ "xaimassist::ui::UiViewModel::ModeDescriptor", "structxaimassist_1_1ui_1_1UiViewModel_1_1ModeDescriptor.html", null ],
    [ "xaimassist::persistence::ModeMetricAggregate", "structxaimassist_1_1persistence_1_1ModeMetricAggregate.html", null ],
    [ "xaimassist::gameplay::ModeOrchestrator", "classxaimassist_1_1gameplay_1_1ModeOrchestrator.html", null ],
    [ "xaimassist::persistence::ModePerformanceSummary", "structxaimassist_1_1persistence_1_1ModePerformanceSummary.html", null ],
    [ "xaimassist::persistence::ModePreferences", "structxaimassist_1_1persistence_1_1ModePreferences.html", null ],
    [ "xaimassist::ui::UiViewModel::ModeSettingDescriptor", "structxaimassist_1_1ui_1_1UiViewModel_1_1ModeSettingDescriptor.html", null ],
    [ "xaimassist::ui::UiViewModel::PerformanceMetricComparison", "structxaimassist_1_1ui_1_1UiViewModel_1_1PerformanceMetricComparison.html", null ],
    [ "xaimassist::core::events::PerformanceStatsEvent", "structxaimassist_1_1core_1_1events_1_1PerformanceStatsEvent.html", null ],
    [ "xaimassist::persistence::PersistenceDatabase", "classxaimassist_1_1persistence_1_1PersistenceDatabase.html", null ],
    [ "xaimassist::persistence::ProfileManager", "classxaimassist_1_1persistence_1_1ProfileManager.html", null ],
    [ "xaimassist::persistence::ProfileRecord", "structxaimassist_1_1persistence_1_1ProfileRecord.html", null ],
    [ "QObject", null, [
      [ "xaimassist::app::TrainingFlowController", "classxaimassist_1_1app_1_1TrainingFlowController.html", null ],
      [ "xaimassist::input::InputManager", "classxaimassist_1_1input_1_1InputManager.html", null ],
      [ "xaimassist::ui::UiViewModel", "classxaimassist_1_1ui_1_1UiViewModel.html", null ]
    ] ],
    [ "xaimassist::core::events::RealtimeStatsEvent", "structxaimassist_1_1core_1_1events_1_1RealtimeStatsEvent.html", null ],
    [ "xaimassist::world::RenderComponent", "structxaimassist_1_1world_1_1RenderComponent.html", null ],
    [ "xaimassist::engine::RenderContext", "classxaimassist_1_1engine_1_1RenderContext.html", null ],
    [ "xaimassist::app::RuntimeLoop", "classxaimassist_1_1app_1_1RuntimeLoop.html", null ],
    [ "xaimassist::app::RuntimeServices", "structxaimassist_1_1app_1_1RuntimeServices.html", null ],
    [ "xaimassist::engine::Scene", "classxaimassist_1_1engine_1_1Scene.html", null ],
    [ "xaimassist::input::SensitivityModel", "classxaimassist_1_1input_1_1SensitivityModel.html", null ],
    [ "xaimassist::persistence::SensitivityPreferences", "structxaimassist_1_1persistence_1_1SensitivityPreferences.html", null ],
    [ "xaimassist::input::SensitivitySettings", "structxaimassist_1_1input_1_1SensitivitySettings.html", null ],
    [ "xaimassist::persistence::SessionHistory", "classxaimassist_1_1persistence_1_1SessionHistory.html", null ],
    [ "xaimassist::persistence::SessionRecord", "structxaimassist_1_1persistence_1_1SessionRecord.html", null ],
    [ "xaimassist::core::events::SessionStartedEvent", "structxaimassist_1_1core_1_1events_1_1SessionStartedEvent.html", null ],
    [ "xaimassist::stats::SessionStatsSnapshot", "structxaimassist_1_1stats_1_1SessionStatsSnapshot.html", null ],
    [ "xaimassist::core::events::SessionStoppedEvent", "structxaimassist_1_1core_1_1events_1_1SessionStoppedEvent.html", null ],
    [ "xaimassist::core::events::SessionSummaryEvent", "structxaimassist_1_1core_1_1events_1_1SessionSummaryEvent.html", null ],
    [ "xaimassist::persistence::SessionValidationResult", "structxaimassist_1_1persistence_1_1SessionValidationResult.html", null ],
    [ "xaimassist::persistence::SettingsManager", "classxaimassist_1_1persistence_1_1SettingsManager.html", null ],
    [ "xaimassist::core::events::ShotFiredEvent", "structxaimassist_1_1core_1_1events_1_1ShotFiredEvent.html", null ],
    [ "xaimassist::core::events::ShotHitEvent", "structxaimassist_1_1core_1_1events_1_1ShotHitEvent.html", null ],
    [ "xaimassist::core::events::ShotMissEvent", "structxaimassist_1_1core_1_1events_1_1ShotMissEvent.html", null ],
    [ "xaimassist::engine::Engine::SphereSpawnRequest", "structxaimassist_1_1engine_1_1Engine_1_1SphereSpawnRequest.html", null ],
    [ "xaimassist::gameplay::SphereTargetSpawnRequest", "structxaimassist_1_1gameplay_1_1SphereTargetSpawnRequest.html", null ],
    [ "xaimassist::stats::StatTracker", "classxaimassist_1_1stats_1_1StatTracker.html", null ],
    [ "xaimassist::gameplay::Target", "classxaimassist_1_1gameplay_1_1Target.html", [
      [ "xaimassist::gameplay::BlinkingTarget", "classxaimassist_1_1gameplay_1_1BlinkingTarget.html", null ],
      [ "xaimassist::gameplay::MovingTarget", "classxaimassist_1_1gameplay_1_1MovingTarget.html", null ],
      [ "xaimassist::gameplay::StaticTarget", "classxaimassist_1_1gameplay_1_1StaticTarget.html", null ],
      [ "xaimassist::gameplay::StrafingTarget", "classxaimassist_1_1gameplay_1_1StrafingTarget.html", null ]
    ] ],
    [ "xaimassist::gameplay::TargetDefinition", "structxaimassist_1_1gameplay_1_1TargetDefinition.html", null ],
    [ "xaimassist::core::events::TargetDestroyedEvent", "structxaimassist_1_1core_1_1events_1_1TargetDestroyedEvent.html", null ],
    [ "xaimassist::gameplay::TargetFactory", "classxaimassist_1_1gameplay_1_1TargetFactory.html", null ],
    [ "xaimassist::persistence::TargetPreferences", "structxaimassist_1_1persistence_1_1TargetPreferences.html", null ],
    [ "xaimassist::core::events::TargetSpawnedEvent", "structxaimassist_1_1core_1_1events_1_1TargetSpawnedEvent.html", null ],
    [ "xaimassist::gameplay::TargetSystem", "classxaimassist_1_1gameplay_1_1TargetSystem.html", null ],
    [ "xaimassist::core::FrameClock::TickResult", "structxaimassist_1_1core_1_1FrameClock_1_1TickResult.html", null ],
    [ "xaimassist::world::TransformComponent", "structxaimassist_1_1world_1_1TransformComponent.html", null ],
    [ "xaimassist::persistence::UiPreferences", "structxaimassist_1_1persistence_1_1UiPreferences.html", null ],
    [ "xaimassist::persistence::WindowPreferences", "structxaimassist_1_1persistence_1_1WindowPreferences.html", null ],
    [ "xaimassist::world::World", "classxaimassist_1_1world_1_1World.html", null ],
    [ "xaimassist::world::WorldRenderSync", "classxaimassist_1_1world_1_1WorldRenderSync.html", null ]
];